### ISSUE TITLE
What is the license of Sorbet-Cocoa?

### ISSUE THREAD

**Issue by optikos** [kylewlacy/sorbet-cocoa#2]
I observe that the license seems to never be specified for Sorbet-Cocoa anywhere in this GitHub repository or in its file prologues atop each file.  May I suggest either the MIT license or the LGPLv3?

**Comment by kylewlacy** [comment]
I was hesitant to add a license since lots of code in this repo wraps APIs published by Apple. I just looked into and it seems like Mono gets away with it without trouble, so I just commited a license (dual-licensed under MIT and Apache 2.0)
